on: [push]

name: CI

jobs:
  test:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.62.0
      - uses: actions-rs/cargo@v1
        name: Test standard syntax
        with:
          command: test
      - uses: actions-rs/cargo@v1
        name: Test PostgreSQL syntax
        with:
          command: test
          args: --features postgresql
      - uses: actions-rs/cargo@v1
        name: Test SQLite syntax
        with:
          command: test
          args: --features sqlite
      - uses: actions-rs/cargo@v1
        name: Test MySQL syntax
        with:
          command: test
          args: --features mysql
